// <auto-generated />
using System;
using MealPlanner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    [Migration("20260120212450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealPlanner.Domain.Meals.PlannedMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal_type");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("Date", "MealType")
                        .IsUnique();

                    b.ToTable("planned_meals", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Recipes.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ingredients");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("steps");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Infrastructure.Persistence.ShoppingListStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheckedItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("checked_items");

                    b.Property<string>("CustomItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_items");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .IsUnique();

                    b.ToTable("shopping_list_states", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Infrastructure.Persistence.UserPreferencesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string[]>("Allergies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergies");

                    b.Property<bool>("AutoGenerateShoppingList")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generate_shopping_list");

                    b.Property<string>("DietaryPreference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dietary_preference");

                    b.Property<string[]>("ExcludedIngredients")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("excluded_ingredients");

                    b.Property<bool>("IncludeLeftovers")
                        .HasColumnType("boolean")
                        .HasColumnName("include_leftovers");

                    b.Property<int>("MealsPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("meals_per_day");

                    b.Property<int>("PlanLength")
                        .HasColumnType("integer")
                        .HasColumnName("plan_length");

                    b.HasKey("Id");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Domain.Meals.PlannedMeal", b =>
                {
                    b.HasOne("MealPlanner.Domain.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");
                });
#pragma warning restore 612, 618
        }
    }
}
